config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
#get 'redboard', to: 'redboard#index', :via => [:post]
#get 'redboard' => 'redboard#options', :via => [:options]
match 'redboard', to: 'redboard#index', via: [:get]
match 'redboard/view/:id', to: 'redboard#view', via: [:get], as: 'board_view'

match 'redboard/api/all', :controller => 'redboard_api', :action => 'index', :via => :get
match 'redboard/api/all', to: 'redboard_api#options', via: [:options]

match 'redboard/api/create', :controller => 'redboard_api', :action => 'create', :via => :post
match 'redboard/api/create', to: 'redboard_api#options', via: [:options]

match 'redboard/api/update/:id', :controller => 'redboard_api', :action => 'update', :via => :post
match 'redboard/api/update/:id', to: 'redboard_api#options', via: [:options]

match 'redboard/api/create-booking', :controller => 'redboard_api', :action => 'createBooking', :via => :post
match 'redboard/api/create-booking', to: 'redboard_api#options', via: [:options]

app/controllers/redboard_controller.rb
class RedboardController < ApplicationController
  before_action :global_authorize

  def index
    @groups = Group.givable.sorted
  end

  def view
    @group_id = params[:id];
    @pusher_app_key = Setting.plugin_void_red_board['pusher_key']
    @pusher_cluster = Setting.plugin_void_red_board['pusher_cluster']
  end

  #
  # User logged in
  #
  def set_user
    @current_user ||= User.current
  end

  #
  # Need Login
  #
  def global_authorize
    set_user
    render_403 unless @current_user.type == 'User'
  end
end

app/views/redboard/index.html.erb
<h1>Boards</h1>

<% user_group_ids = @current_user.group_ids %>

<ul>
<% @groups.each do |g| %>
    <% if (user_group_ids.include?(g.id) || @current_user.admin) %>
    <li><%= link_to(g.name, board_view_path(g.id)) %></li>
    <% end %>
<% end %>
</ul>

app/views/redboard/view.html.erb
<script src="https://js.pusher.com/7.0/pusher.min.js"></script>
<script>
    Pusher.logToConsole = true;

    var pusher = new Pusher('<%= @pusher_app_key %>', {
      cluster: '<%= @pusher_cluster %>'
    });
   var channel = pusher.subscribe('redmine');
   channel.bind('idea-event', function(data) {
        const e = new CustomEvent("p2p.data", {detail: data});
        window.dispatchEvent(e)
    });

    var board_group_id = '<%= @group_id %>'

</script>

    <link href="/plugin_assets/void_red_board/app/static/css/2.0c14234b.chunk.css" rel="stylesheet">
    <link href="/plugin_assets/void_red_board/app/static/css/main.01fdc67a.chunk.css" rel="stylesheet">
    <style>
    .redBoardApp {
        overflow-x: auto;
    }
    	#header, #footer {
    		display: none;
    	}
    	#main.nosidebar #content {
    width: 100%;
    padding: 0;
}
    </style>

<div id="root"></div>
<script>!function (e) { function r(r) { for (var n, l, a = r[0], f = r[1], i = r[2], c = 0, s = []; c < a.length; c++)l = a[c], Object.prototype.hasOwnProperty.call(o, l) && o[l] && s.push(o[l][0]), o[l] = 0; for (n in f) Object.prototype.hasOwnProperty.call(f, n) && (e[n] = f[n]); for (p && p(r); s.length;)s.shift()(); return u.push.apply(u, i || []), t() } function t() { for (var e, r = 0; r < u.length; r++) { for (var t = u[r], n = !0, a = 1; a < t.length; a++) { var f = t[a]; 0 !== o[f] && (n = !1) } n && (u.splice(r--, 1), e = l(l.s = t[0])) } return e } var n = {}, o = { 1: 0 }, u = []; function l(r) { if (n[r]) return n[r].exports; var t = n[r] = { i: r, l: !1, exports: {} }; return e[r].call(t.exports, t, t.exports, l), t.l = !0, t.exports } l.m = e, l.c = n, l.d = function (e, r, t) { l.o(e, r) || Object.defineProperty(e, r, { enumerable: !0, get: t }) }, l.r = function (e) { "undefined" != typeof Symbol && Symbol.toStringTag && Object.defineProperty(e, Symbol.toStringTag, { value: "Module" }), Object.defineProperty(e, "__esModule", { value: !0 }) }, l.t = function (e, r) { if (1 & r && (e = l(e)), 8 & r) return e; if (4 & r && "object" == typeof e && e && e.__esModule) return e; var t = Object.create(null); if (l.r(t), Object.defineProperty(t, "default", { enumerable: !0, value: e }), 2 & r && "string" != typeof e) for (var n in e) l.d(t, n, function (r) { return e[r] }.bind(null, n)); return t }, l.n = function (e) { var r = e && e.__esModule ? function () { return e.default } : function () { return e }; return l.d(r, "a", r), r }, l.o = function (e, r) { return Object.prototype.hasOwnProperty.call(e, r) }, l.p = "/"; var a = this.webpackJsonpredboard = this.webpackJsonpredboard || [], f = a.push.bind(a); a.push = r, a = a.slice(); for (var i = 0; i < a.length; i++)r(a[i]); var p = f; t() }([])</script>
<script src="/plugin_assets/void_red_board/app/static/js/2.5d7670e6.chunk.js"></script>
<script src="/plugin_assets/void_red_board/app/static/js/main.231ff537.chunk.js"></script>